mnmn: SmartThingsCommunity
vid: 7c75153c-5c2e-32b9-9609-e4ae6e646cea
version: 0.0.1
type: profile
dashboard:
  states:
    - component: main
      capability: stsolutions.demandResponseStatus
      version: 1
      idx: 0
      group: main
      values: []
      composite: false
  actions: []
detailView:
  - component: main
    capability: stsolutions.demandResponseMode
    version: 1
    values: []
    patch: []
  - component: main
    capability: stsolutions.demandResponseStatus
    version: 1
    values: []
    patch: []
  - component: main
    capability: stsolutions.message
    version: 1
    values: []
    patch: []
automation:
  conditions:
    - component: main
      capability: stsolutions.demandResponseMode
      version: 1
      values: []
      patch: []
      exclusion: []
    - component: main
      capability: stsolutions.demandResponseStatus
      version: 1
      values: []
      patch: []
      exclusion: []
  actions:
    - component: main
      capability: stsolutions.demandResponseMode
      version: 1
      values: []
      patch: []
      exclusion: []
presentationId: 7c75153c-5c2e-32b9-9609-e4ae6e646cea
manufacturerName: SmartThingsCommunity
